BEGIN;
MERGE INTO public.dm_funcionario df
USING
	(
		SELECT DISTINCT 
					ID_FUNCIONARIO,
					ID_CARGO,
					NOME_FUNCIONARIO,
					CPF
		from dblink('host=localhost user=postgres password=postgres dbname=lojabi',
		$$
			SELECT 	
					ID_FUNCIONARIO, 
					ID_CARGO, 
					NOME_FUNCIONARIO,
					CPF
		FROM funcionario
		$$) AS funcionario
					(ID_FUNCIONARIO INT,
					ID_CARGO INT,
					NOME_FUNCIONARIO VARCHAR(100),
					CPF CHAR(15))
		ORDER BY 1
	) MERGE_SUBQUERY
ON (
		df.NK_ID_FUNCIONARIO = MERGE_SUBQUERY.ID_FUNCIONARIO
	)
WHEN NOT MATCHED THEN 

INSERT 
		(
			SK_ID_CARGO,
			NK_ID_FUNCIONARIO,
			NOME_FUNCIONARIO,
			CPF
		)
VALUES 
		(
			MERGE_SUBQUERY.ID_CARGO,
			MERGE_SUBQUERY.ID_FUNCIONARIO,
			MERGE_SUBQUERY.NOME_FUNCIONARIO,
			MERGE_SUBQUERY.CPF
		)
WHEN MATCHED THEN 

UPDATE SET 
			SK_ID_CARGO 			=	MERGE_SUBQUERY.ID_CARGO,
			NK_ID_FUNCIONARIO		=	MERGE_SUBQUERY.ID_FUNCIONARIO,
			NOME_FUNCIONARIO		=	MERGE_SUBQUERY.NOME_FUNCIONARIO,
			CPF						=	MERGE_SUBQUERY.CPF;
commit;